### ISSUE TITLE
build: msys2 compile errors

### ISSUE THREAD

**Issue by matkuki** [mrgaturus/npainter#12]
Hi,

I'm trying to build on Windows 10 x64 in MSYS2 and get this during the pacman installation process:
![image](https://github.com/user-attachments/assets/5cb12549-0f7b-4129-979c-6b9f5a47297c)
Any ideas?

**Comment by mrgaturus** [comment]
hi, thank you trying the program!
looks like the packages were not downloaded properly, this is more a problem by MSYS2 instead this project.
Try clear cache, updating repositories, and try the build script again
```sh
pacman -Scc
pacman -Syu
./build_win32.sh
```
I will keep this issue open because i forgot an additional package in the build script:
```sh
pacman -S mingw-w64-x86_64-librsvg
```

**Comment by matkuki** [comment]
Thanks, that fixed the `pacman` errors 👍

This part also doesn't work on MSYS2:
![image](https://github.com/user-attachments/assets/a20b2834-d19b-444a-a48d-c50dae6ad7b2)
It seems that the `nimble` path isn't constructed correctly, and the `cp` command gives a `path doesn't exist` error, it seems to cut out the Windows drive letter when getting the `nimble` directory with `$NIMBLE_PATH`.
I got around this by doing this part manually and everything else works.

**Comment by mrgaturus** [comment]
I think i need try install Nim from zip file and `finish.exe` instead use `choosenim`

**Comment by mrgaturus** [comment]
looking nim install page it says i can use `%USERPROFILE%\.nimble\bin`

**Comment by mrgaturus** [comment]
added the dependencies and i fixed the build script, let me know if i properly fixed it
