### ISSUE TITLE
compilation from git sources fails: ux/main/menu.nim(165, 50) Error: attempting to call undeclared routine: 'clear'

### ISSUE THREAD

**Issue by Popolon** [mrgaturus/npainter#17]
Hi, thanks for your interesting piece of software.

When I try to build it on Arch Linux (nim 2.0.8), with last git clone, compilation fails at this point:
<pre>
  Success:  nogui installed successfully.
   Building npainter/npainter using c backend
/home/popolon/app/npainter/src/ux/main/menu.nim(26, 1) template/generic instantiation of `controller` from here
/home/popolon/app/npainter/src/ux/main/menu.nim(165, 50) Error: attempting to call undeclared routine: 'clear'
       Tip: 112 messages have been suppressed, use --verbose to show them.
nimble.nim(304)          buildFromDir

    Error:  Build failed for the package: npainter
</pre>

The missing clear() is in this procedure in ux/main/menu.nim:
<pre>
  proc menuLogo: UXNoClick =
    result = noclick button(iconLogo, self.dummy).clear()
</pre>

**Comment by mrgaturus** [comment]
hi, right now the `master` branch is not compiling, try the `mask` branch. i did breaking changes in the gui toolkit, so should be aware to choose a version of the gui before i start working in a new feature branch

**Comment by mrgaturus** [comment]
still opened meanwhile i merge it into `master`
